import type { Session } from "./types";

export const SESSIONS: Session[] = [
  {
    id: 1,
    title: "Year 11 — Binary & Data Representation",
    date: "2025-06-21",
    duration: "1:09:45",
    subject: "Computer Science",
    teacherTalk: 68,
    studentTalk: 22,
    silence: 10,
    indicators: {
      pacing: {
        value: 142,
        unit: "wpm",
        label: "Speaking Pace",
        status: "good",
      },
      pauses: {
        value: 1.8,
        unit: "s avg",
        label: "Avg Pause Length",
        status: "good",
      },
      fillers: {
        value: 14,
        unit: "instances",
        label: "Filler Words",
        status: "high",
      },
      prosody: {
        value: 61,
        unit: "/ 100",
        label: "Prosodic Variation",
        status: "good",
      },
      turns: {
        value: 18,
        unit: "exchanges",
        label: "Turn-Taking Events",
        status: "low",
      },
      longestMonologue: {
        value: "16:30",
        unit: "min",
        label: "Longest Monologue",
        status: "high",
      },
    },
    prompts: [
      "You spoke for over 16 minutes without a student contribution. What conditions in the room might have led to this, and how could you create a natural break point?",
      "Your filler word count was above your usual baseline. Were there moments where pausing silently might have felt more confident than filling the space?",
      "Student talk sat at 22% today. What one question could you have posed to shift more cognitive load onto the students during the binary conversion section?",
    ],
  },
  {
    id: 2,
    title: "Year 9 — Intro to Algorithms",
    date: "2025-06-18",
    duration: "58:30",
    subject: "Computer Science",
    teacherTalk: 55,
    studentTalk: 35,
    silence: 10,
    indicators: {
      pacing: {
        value: 128,
        unit: "wpm",
        label: "Speaking Pace",
        status: "good",
      },
      pauses: {
        value: 2.3,
        unit: "s avg",
        label: "Avg Pause Length",
        status: "good",
      },
      fillers: {
        value: 7,
        unit: "instances",
        label: "Filler Words",
        status: "good",
      },
      prosody: {
        value: 74,
        unit: "/ 100",
        label: "Prosodic Variation",
        status: "good",
      },
      turns: {
        value: 31,
        unit: "exchanges",
        label: "Turn-Taking Events",
        status: "good",
      },
      longestMonologue: {
        value: "8:45",
        unit: "min",
        label: "Longest Monologue",
        status: "good",
      },
    },
    prompts: [
      "This was one of your most balanced sessions in terms of talk ratio. What did you do differently at the start of the lesson that seemed to invite more student participation?",
      "Your prosodic variation score was notably high. Were there specific moments where you consciously modulated your voice, or did it happen naturally?",
    ],
  },
  {
    id: 3,
    title: "Year 12 — Sorting Algorithms Deep Dive",
    date: "2025-06-14",
    duration: "1:14:10",
    subject: "Computer Science",
    teacherTalk: 72,
    studentTalk: 18,
    silence: 10,
    indicators: {
      pacing: {
        value: 155,
        unit: "wpm",
        label: "Speaking Pace",
        status: "high",
      },
      pauses: {
        value: 1.1,
        unit: "s avg",
        label: "Avg Pause Length",
        status: "high",
      },
      fillers: {
        value: 22,
        unit: "instances",
        label: "Filler Words",
        status: "high",
      },
      prosody: {
        value: 48,
        unit: "/ 100",
        label: "Prosodic Variation",
        status: "low",
      },
      turns: {
        value: 11,
        unit: "exchanges",
        label: "Turn-Taking Events",
        status: "low",
      },
      longestMonologue: {
        value: "21:05",
        unit: "min",
        label: "Longest Monologue",
        status: "high",
      },
    },
    prompts: [
      "Your speaking pace was your fastest on record at 155wpm. This sometimes correlates with anxiety or time pressure. Was there an external factor driving the pace today?",
      "A 21-minute monologue occurred during the merge sort explanation. How might chunking this into smaller segments with retrieval checks have changed the students' experience?",
      "Prosodic variation was below your average, which can cause students to disengage. What anchors could you use to remind yourself to vary your delivery during technical explanations?",
    ],
  },
  {
    id: 4,
    title: "Year 10 — Networks & Protocols",
    date: "2025-06-10",
    duration: "1:01:20",
    subject: "Computer Science",
    teacherTalk: 60,
    studentTalk: 28,
    silence: 12,
    indicators: {
      pacing: {
        value: 134,
        unit: "wpm",
        label: "Speaking Pace",
        status: "good",
      },
      pauses: {
        value: 2.0,
        unit: "s avg",
        label: "Avg Pause Length",
        status: "good",
      },
      fillers: {
        value: 9,
        unit: "instances",
        label: "Filler Words",
        status: "good",
      },
      prosody: {
        value: 67,
        unit: "/ 100",
        label: "Prosodic Variation",
        status: "good",
      },
      turns: {
        value: 24,
        unit: "exchanges",
        label: "Turn-Taking Events",
        status: "good",
      },
      longestMonologue: {
        value: "11:20",
        unit: "min",
        label: "Longest Monologue",
        status: "high",
      },
    },
    prompts: [
      "The silence ratio was slightly higher than usual at 12%. Were these productive thinking pauses, or did they indicate confusion? How could you distinguish between the two in the moment?",
      "Your longest monologue ran to just over 11 minutes during the TCP/IP stack explanation. At what point did you notice student attention beginning to drift, if at all?",
    ],
  },
  {
    id: 5,
    title: "Year 11 — Boolean Logic & Logic Gates",
    date: "2025-06-05",
    duration: "1:05:00",
    subject: "Computer Science",
    teacherTalk: 65,
    studentTalk: 25,
    silence: 10,
    indicators: {
      pacing: {
        value: 138,
        unit: "wpm",
        label: "Speaking Pace",
        status: "good",
      },
      pauses: {
        value: 1.9,
        unit: "s avg",
        label: "Avg Pause Length",
        status: "good",
      },
      fillers: {
        value: 11,
        unit: "instances",
        label: "Filler Words",
        status: "good",
      },
      prosody: {
        value: 63,
        unit: "/ 100",
        label: "Prosodic Variation",
        status: "good",
      },
      turns: {
        value: 20,
        unit: "exchanges",
        label: "Turn-Taking Events",
        status: "good",
      },
      longestMonologue: {
        value: "13:50",
        unit: "min",
        label: "Longest Monologue",
        status: "high",
      },
    },
    prompts: [
      "Boolean logic often trips students up because of the mapping between everyday language and formal logic. How did you check that students had internalised the distinction rather than just memorising symbols?",
      "You maintained a consistent pace throughout — what strategies are you using to self-monitor pace during content-heavy lessons?",
    ],
  },
  {
    id: 6,
    title: "Year 9 — Variables & Data Types",
    date: "2025-05-30",
    duration: "55:15",
    subject: "Computer Science",
    teacherTalk: 52,
    studentTalk: 38,
    silence: 10,
    indicators: {
      pacing: {
        value: 121,
        unit: "wpm",
        label: "Speaking Pace",
        status: "good",
      },
      pauses: {
        value: 2.6,
        unit: "s avg",
        label: "Avg Pause Length",
        status: "good",
      },
      fillers: {
        value: 5,
        unit: "instances",
        label: "Filler Words",
        status: "good",
      },
      prosody: {
        value: 79,
        unit: "/ 100",
        label: "Prosodic Variation",
        status: "good",
      },
      turns: {
        value: 38,
        unit: "exchanges",
        label: "Turn-Taking Events",
        status: "good",
      },
      longestMonologue: {
        value: "6:10",
        unit: "min",
        label: "Longest Monologue",
        status: "good",
      },
    },
    prompts: [
      "This session had your highest turn-taking count and lowest filler word score to date. What was different about how you planned or entered this lesson?",
      "Student talk reached 38% — your highest ratio across all recorded sessions. What question types seemed to unlock the most student contribution?",
    ],
  },
  {
    id: 7,
    title: "Year 12 — Complexity & Big-O Notation",
    date: "2025-05-24",
    duration: "1:10:30",
    subject: "Computer Science",
    teacherTalk: 74,
    studentTalk: 16,
    silence: 10,
    indicators: {
      pacing: {
        value: 148,
        unit: "wpm",
        label: "Speaking Pace",
        status: "high",
      },
      pauses: {
        value: 1.3,
        unit: "s avg",
        label: "Avg Pause Length",
        status: "high",
      },
      fillers: {
        value: 19,
        unit: "instances",
        label: "Filler Words",
        status: "high",
      },
      prosody: {
        value: 52,
        unit: "/ 100",
        label: "Prosodic Variation",
        status: "low",
      },
      turns: {
        value: 9,
        unit: "exchanges",
        label: "Turn-Taking Events",
        status: "low",
      },
      longestMonologue: {
        value: "18:40",
        unit: "min",
        label: "Longest Monologue",
        status: "high",
      },
    },
    prompts: [
      "Big-O is abstract by nature — student talk at 16% suggests they may have been passive recipients rather than active sense-makers. What analogies or activities could shift this in future?",
      "Your pause length average dropped below 1.5 seconds in several sections. Research suggests pauses of 3+ seconds after a question significantly increase the quality of student responses.",
    ],
  },
  {
    id: 8,
    title: "Year 10 — Cybersecurity Basics",
    date: "2025-05-19",
    duration: "1:00:00",
    subject: "Computer Science",
    teacherTalk: 58,
    studentTalk: 30,
    silence: 12,
    indicators: {
      pacing: {
        value: 131,
        unit: "wpm",
        label: "Speaking Pace",
        status: "good",
      },
      pauses: {
        value: 2.1,
        unit: "s avg",
        label: "Avg Pause Length",
        status: "good",
      },
      fillers: {
        value: 8,
        unit: "instances",
        label: "Filler Words",
        status: "good",
      },
      prosody: {
        value: 70,
        unit: "/ 100",
        label: "Prosodic Variation",
        status: "good",
      },
      turns: {
        value: 27,
        unit: "exchanges",
        label: "Turn-Taking Events",
        status: "good",
      },
      longestMonologue: {
        value: "9:55",
        unit: "min",
        label: "Longest Monologue",
        status: "good",
      },
    },
    prompts: [
      "Cybersecurity tends to engage students naturally through real-world relevance. Did you notice a difference in the quality of student questions compared to more abstract topics?",
      "Your talk ratio was well-balanced today. Were there moments where you consciously held back from filling silence to let students formulate responses?",
    ],
  },
  {
    id: 9,
    title: "Year 11 — CPU Architecture & Fetch-Decode-Execute",
    date: "2025-05-13",
    duration: "1:08:00",
    subject: "Computer Science",
    teacherTalk: 70,
    studentTalk: 20,
    silence: 10,
    indicators: {
      pacing: {
        value: 145,
        unit: "wpm",
        label: "Speaking Pace",
        status: "good",
      },
      pauses: {
        value: 1.7,
        unit: "s avg",
        label: "Avg Pause Length",
        status: "good",
      },
      fillers: {
        value: 16,
        unit: "instances",
        label: "Filler Words",
        status: "high",
      },
      prosody: {
        value: 59,
        unit: "/ 100",
        label: "Prosodic Variation",
        status: "low",
      },
      turns: {
        value: 15,
        unit: "exchanges",
        label: "Turn-Taking Events",
        status: "low",
      },
      longestMonologue: {
        value: "14:25",
        unit: "min",
        label: "Longest Monologue",
        status: "high",
      },
    },
    prompts: [
      "The fetch-decode-execute cycle is highly sequential — did this linearity affect your delivery style? How might a non-linear approach (e.g. starting from the execute stage) have changed engagement?",
      "Prosodic variation was below average during what appears to be the register explanation section. What physical or vocal warm-up practices do you use before lessons with dense technical content?",
    ],
  },
];
